spring:
  application:
    name: shopflow-backend

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:54324/shopflow}
    username: ${DB_USERNAME:shopflow}
    password: ${DB_PASSWORD:shopflow}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC

  flyway:
    enabled: true
    locations: classpath:db/migration
    group: true

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:63793}
      password: "${REDIS_PASSWORD:}"
      timeout: 2s

  cache:
    type: redis
    redis:
      key-prefix: "shopflow:"
      use-key-prefix: true
      cache-null-values: false
      time-to-live: 10m

  threads:
    virtual:
      enabled: true

  web:
    error:
      include-message: never
      include-binding-errors: never

server:
  port: ${SERVER_PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health,info

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs