spring:
  application:
    name: shopflow-backend

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:54324/shopflow}
    username: ${DB_USERNAME:shopflow}
    password: ${DB_PASSWORD:shopflow}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC

  flyway:
    enabled: true
    locations: classpath:db/migration
    group: true

  threads:
    virtual:
      enabled: true
  web:
    error:
      include-message: never
      include-binding-errors: never

server:
  port: ${SERVER_PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health,info

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs