CREATE TABLE cart_items
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    cart_id             BIGINT                                  NOT NULL,
    product_id          BIGINT                                  NOT NULL,
    quantity            INTEGER                                 NOT NULL,
    unit_price_snapshot DECIMAL(19, 2)                          NOT NULL,
    CONSTRAINT pk_cart_items PRIMARY KEY (id)
);

CREATE TABLE carts
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    customer_email VARCHAR(180)                            NOT NULL,
    status         VARCHAR(30)                             NOT NULL,
    created_at     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_carts PRIMARY KEY (id)
);

CREATE TABLE categories
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(120)                            NOT NULL,
    slug VARCHAR(140)                            NOT NULL,
    CONSTRAINT pk_categories PRIMARY KEY (id)
);

CREATE TABLE order_items
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_id     BIGINT                                  NOT NULL,
    product_id   BIGINT                                  NOT NULL,
    product_sku  VARCHAR(80)                             NOT NULL,
    product_name VARCHAR(180)                            NOT NULL,
    quantity     INTEGER                                 NOT NULL,
    unit_price   DECIMAL(19, 2)                          NOT NULL,
    line_total   DECIMAL(19, 2)                          NOT NULL,
    CONSTRAINT pk_order_items PRIMARY KEY (id)
);

CREATE TABLE orders
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_number         VARCHAR(40)                             NOT NULL,
    customer_name        VARCHAR(160)                            NOT NULL,
    customer_email       VARCHAR(180)                            NOT NULL,
    customer_phone       VARCHAR(40)                             NOT NULL,
    status               VARCHAR(40)                             NOT NULL,
    payment_status       VARCHAR(40)                             NOT NULL,
    total_price          DECIMAL(19, 2)                          NOT NULL,
    created_at           TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at           TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    paid_at              TIMESTAMP WITHOUT TIME ZONE,
    cancelled_at         TIMESTAMP WITHOUT TIME ZONE,
    delivery_street      VARCHAR(180)                            NOT NULL,
    delivery_city        VARCHAR(120)                            NOT NULL,
    delivery_postal_code VARCHAR(40)                             NOT NULL,
    delivery_country     VARCHAR(80)                             NOT NULL,
    CONSTRAINT pk_orders PRIMARY KEY (id)
);

CREATE TABLE payments
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_id            BIGINT                                  NOT NULL,
    provider            VARCHAR(40)                             NOT NULL,
    status              VARCHAR(40)                             NOT NULL,
    amount              DECIMAL(19, 2)                          NOT NULL,
    external_payment_id VARCHAR(100),
    failure_reason      VARCHAR(500),
    created_at          TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at          TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_payments PRIMARY KEY (id)
);

CREATE TABLE products
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    sku               VARCHAR(80)                             NOT NULL,
    name              VARCHAR(180)                            NOT NULL,
    description       VARCHAR(2000)                           NOT NULL,
    price             DECIMAL(19, 2)                          NOT NULL,
    stock_quantity    INTEGER                                 NOT NULL,
    reserved_quantity INTEGER                                 NOT NULL,
    active            BOOLEAN                                 NOT NULL,
    category_id       BIGINT                                  NOT NULL,
    version           BIGINT                                  NOT NULL,
    created_at        TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at        TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_products PRIMARY KEY (id)
);

CREATE TABLE stock_movements
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product_id   BIGINT                                  NOT NULL,
    product_sku  VARCHAR(80)                             NOT NULL,
    type         VARCHAR(60)                             NOT NULL,
    quantity     INTEGER                                 NOT NULL,
    reason       VARCHAR(500)                            NOT NULL,
    order_number VARCHAR(40),
    created_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_stock_movements PRIMARY KEY (id)
);

ALTER TABLE categories
    ADD CONSTRAINT uc_categories_name UNIQUE (name);

ALTER TABLE categories
    ADD CONSTRAINT uc_categories_slug UNIQUE (slug);

ALTER TABLE orders
    ADD CONSTRAINT uc_orders_ordernumber UNIQUE (order_number);

ALTER TABLE payments
    ADD CONSTRAINT uc_payments_order UNIQUE (order_id);

ALTER TABLE products
    ADD CONSTRAINT uc_products_sku UNIQUE (sku);

ALTER TABLE cart_items
    ADD CONSTRAINT FK_CART_ITEMS_ON_CART FOREIGN KEY (cart_id) REFERENCES carts (id);

ALTER TABLE cart_items
    ADD CONSTRAINT FK_CART_ITEMS_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES products (id);

ALTER TABLE order_items
    ADD CONSTRAINT FK_ORDER_ITEMS_ON_ORDER FOREIGN KEY (order_id) REFERENCES orders (id);

ALTER TABLE payments
    ADD CONSTRAINT FK_PAYMENTS_ON_ORDER FOREIGN KEY (order_id) REFERENCES orders (id);

ALTER TABLE products
    ADD CONSTRAINT FK_PRODUCTS_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES categories (id);